# Secrets are managed via SSM Parameter Store.
#
# The API key parameter is created with a placeholder and then set manually
# (aws ssm put-parameter --overwrite). `ignore_changes = [value]` keeps
# Terraform from clobbering the real key on the next apply.
resource "aws_ssm_parameter" "ollama_api_key" {
  name  = "/${var.project}/ollama-api-key"
  type  = "SecureString"
  value = "PLACEHOLDER_SET_BY_MASTER"

  lifecycle {
    ignore_changes = [value]
  }
}

# Non-secret: model names are managed by Terraform.
resource "aws_ssm_parameter" "ollama_model" {
  name  = "/${var.project}/ollama-model"
  type  = "String"
  value = var.ollama_model
}

# Embedding model/provider selector. "local-hashed[-N]" = stdlib feature
# hashing (no network); any other value = Ollama /api/embed model name.
resource "aws_ssm_parameter" "embedding_model" {
  name  = "/${var.project}/embedding-model"
  type  = "String"
  value = var.embedding_model
}

# API key for the demo/search API — generated by API Gateway, mirrored to
# SSM (SecureString). Plaintext lives in Terraform state (gitignored).
resource "aws_ssm_parameter" "api_key" {
  name  = "/${var.project}/api-key"
  type  = "SecureString"
  value = aws_api_gateway_api_key.demo.value
}