resource "aws_ssm_parameter" "llm_provider" {
  name  = "/${var.project}/llm-provider"
  type  = "String"
  value = var.llm_provider
}

# Secrets are managed via SSM Parameter Store.
#
# The API key parameter is created with a placeholder and then set manually
# (aws ssm put-parameter --overwrite). `ignore_changes = [value]` keeps
# Terraform from clobbering the real key on the next apply.
resource "aws_ssm_parameter" "ollama_api_key" {
  name  = "/${var.project}/ollama-api-key"
  type  = "SecureString"
  value = "PLACEHOLDER_SET_BY_MASTER"

  lifecycle {
    ignore_changes = [value]
  }
}

# Non-secret: model names are managed by Terraform.
resource "aws_ssm_parameter" "ollama_model" {
  name  = "/${var.project}/ollama-model"
  type  = "String"
  value = var.ollama_model
}

# Embedding model/provider selector. "bedrock:<model-id>" = AWS Bedrock
# InvokeModel (e.g. bedrock:amazon.titan-embed-text-v2:0); "local-hashed[-N]"
# = stdlib feature hashing (fallback, no network); any other value = Ollama
# /api/embed model name.
#
# Value is managed MANUALLY (currently local-hashed-256: Bedrock throttles
# aggressively on new accounts). ignore_changes keeps terraform apply from
# reverting the live value to the variable default — same pattern as the
# API key above. The corpus records each article's embedding_model, so the
# manual value must stay consistent with the data (see search_handler.py).
resource "aws_ssm_parameter" "embedding_model" {
  name  = "/${var.project}/embedding-model"
  type  = "String"
  value = "local-hashed-256"

  lifecycle {
    ignore_changes = [value]
  }
}

# API key for the demo/search API — generated by API Gateway, mirrored to
# SSM (SecureString). Plaintext lives in Terraform state (gitignored).
resource "aws_ssm_parameter" "api_key" {
  name  = "/${var.project}/api-key"
  type  = "SecureString"
  value = aws_api_gateway_api_key.demo.value
}